# Generated by Django 2.2.7 on 2019-11-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitador',
            options={'ordering': ['nombreCapellan'], 'verbose_name': 'Visitadore'},
        ),
        migrations.RenameField(
            model_name='visitador',
            old_name='nombre',
            new_name='nombreCapellan',
        ),
    ]
