# Generated by Django 2.2.7 on 2019-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_auto_20191127_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitador',
            name='pdf',
            field=models.FileField(null='true', upload_to='pdf/'),
        ),
    ]
